// <auto-generated />
using System;
using API_RegistroInterno.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_RegistroInterno.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305162425_Primera Migracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_RegistroInterno.Entities.UsuarioClientesExternos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("actualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtmActualizacion");

                    b.Property<string>("apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchApellido1");

                    b.Property<string>("apellido2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchApellido2");

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchCelular");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchClave");

                    b.Property<DateTime>("creacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtmCreacion");

                    b.Property<string>("documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchDocumento");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchEmail");

                    b.Property<int>("estado")
                        .HasColumnType("int")
                        .HasColumnName("intEstado");

                    b.Property<DateTime>("expedicion")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtmExpidicion");

                    b.Property<int>("intentosFallidos")
                        .HasColumnType("int")
                        .HasColumnName("intIntentosFallidos");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchNombre");

                    b.Property<string>("nombre1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchNombre1");

                    b.Property<string>("nombre2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchNombre2");

                    b.Property<string>("tipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vchTipoDocumento");

                    b.Property<DateTime>("ultimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtmUltimoAcceso");

                    b.HasKey("id");

                    b.ToTable("tblUsuariosClientesExternos", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
